- id: 1
  frame: robot_map
  position: [-0.039752490235147375, 4.008169385284304, 0.1268413218267256]
  orientation: [0.0, 0.0, 0.6893812536282928, 0.7243987073055029]
  max_distance: 2.0
  pose_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05]
- id: frame_1
  frame: robot_map
  position: [-1.035352513223648, 3.9882494983650787, 0.1838058233229674]
  orientation: [0.0, 0.0, 0.6903032564511474, 0.72352015461419]
  max_distance: 5.0
  pose_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05]
- id: 2
  frame: robot_map
  position: [0.43800800884446806, 4.015525259451554, 0.1275999987825437]
  orientation: [0.0, 0.0, 0.7093695752374928, 0.7048367227432033]
  max_distance: 1.25
  pose_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05]
