TrajectoryPlannerROS:
  max_vel_x: 1.0 #0.45
  min_vel_x: 0.25 #0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.3

  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  yaw_goal_tolerance: 0.5 #0.3
  xy_goal_tolerance: 0.2 #No stava

  path_distance_bias: 1.0

  holonomic_robot: true
