obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.5, -0.275], [0.5, 0.275], [-0.5,0.275], [-0.5, -0.275]]
inflation_radius: 0.55

observation_sources: hokuyo_laser

hokuyo_laser: {sensor_frame: hokuyo_laser_link, data_type: LaserScan, topic: hokuyo_laser_topic, marking: true, clearing: true}

