global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  static_map: true
  # robot radius +safety_delta 0.25 + 0.02
  # set to permit drawing a trajectory through the narrowest door
  inflation_radius: 0.35   
  
