local_costmap:
  global_frame: /odom
#  global_frame: /odom_combined
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  #width: 6.0
  #height: 6.0
  #resolution: 0.01 #0.05
  width: 5.0
  height: 5.0
  resolution: 0.05 #0.05
  
  # robot radius set to min to pass near obstacles
  #inflation_radius: 0.060   
  inflation_radius: 0.015   
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
