joint_pan_position_controller:
  type: velocity_controllers/JointPositionController
  joint: $(arg prefix)front_ptz_camera_pan_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint_tilt_position_controller:
  type: velocity_controllers/JointPositionController
  joint: $(arg prefix)front_ptz_camera_tilt_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}


robotnik_base_control:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : ['$(arg prefix)front_left_wheel_joint','$(arg prefix)back_left_wheel_joint']
  right_wheel : ['$(arg prefix)front_right_wheel_joint','$(arg prefix)back_right_wheel_joint']
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.470 #def 0.433
  wheel_radius : 0.11 #def 0.0762

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: $(arg prefix)base_footprint
  odom_frame_id: $(arg prefix)odom
  enable_odom_tf: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 3.0 #1.5 # m/s
      min_velocity           : -3.0 #-1.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 6.0 #3.00  # m/s^2
      min_acceleration       : -6.0 #-3.00 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 6.0 #3.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0 #3.0  # rad/s^2


joint_read_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0
